import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const data=JSON.parse(readFileSync(resolve(root,'data/catalog.json'),'utf8'));
const html=readFileSync(resolve(root,'index.html'),'utf8');
const app=readFileSync(resolve(root,'app.js'),'utf8');
const simpleCss=readFileSync(resolve(root,'shop-simple.css'),'utf8');

test('catalogue keeps all expected products and media',()=>{assert.equal(data.products.length,76);assert.equal(data.media.length,275);assert.equal(new Set(data.products.map(x=>x.id)).size,76);assert.equal(new Set(data.media.map(x=>x.id)).size,275);});
test('Surface listings preserve the supplied prices and distinct specifications',()=>{const ids=['surface-laptop-3','surface-laptop-4-i5','surface-laptop-4-i7'];const products=ids.map(id=>data.products.find(x=>x.id===id));assert(products.every(Boolean));assert.deepEqual(products.map(x=>x.price),[880000,980000,1180000]);assert.deepEqual(products.map(x=>x.ram),[8,16,16]);assert.deepEqual(products.map(x=>x.cpu),['Intel Core i5-1035G7 · 1.9GHz','11th Gen Intel Core i5-1145G7 · 2.6GHz','11th Gen Intel Core i7-1185G7 · 3.0GHz']);assert.deepEqual(products.map(x=>x.screen),['14” (supplied)','14” (supplied)','Confirm size']);assert(products.every(x=>new Set([x.image,...x.photos]).size===8));});
test('all eight supplied Surface photos are intentionally shared by the three listings',()=>{const expected=['surface-laptop-3','surface-laptop-4-i5','surface-laptop-4-i7'];const media=data.media.filter(x=>x.id.startsWith('surface-laptop-shared-'));assert.equal(media.length,8);for(const item of media){assert.deepEqual(item.products,expected);assert.equal(item.kind,'photo');assert(existsSync(resolve(root,item.src)),item.src);}});
test('browser catalogue is exactly synchronized with JSON',()=>{const source=readFileSync(resolve(root,'catalog.js'),'utf8').trim();assert(source.startsWith('window.SHOP_DATA = '));const browserData=JSON.parse(source.slice('window.SHOP_DATA = '.length,-1));assert.deepEqual(browserData,data);});
test('all local media files and product media references resolve',()=>{const media=new Map(data.media.map(x=>[x.id,x]));for(const m of data.media){assert(existsSync(resolve(root,m.src)),m.src);assert(existsSync(resolve(root,m.thumb)),m.thumb);}for(const p of data.products){for(const id of [p.image,p.flyer,...p.photos].filter(Boolean))assert(media.has(id),`${p.id}: ${id}`);}});
test('HP 1030 G7 gallery and media search do not contain HP 1040 G6 photos',()=>{const p=data.products.find(x=>x.id==='hp1030');assert.deepEqual(p.photos,['recovered-1002319517','recovered-1002319518','recovered-1002319516','recovered-1002319519','recovered-1002319522','recovered-1002319521','recovered-1002319520']);assert(p.photos.every(id=>!id.startsWith('recovered-100231956')));for(const m of data.media.filter(x=>x.id.startsWith('recovered-100231956'))){assert.deepEqual(m.products,['hp1040g6']);assert.equal(m.searchText,'HP EliteBook x360 1040 G6');assert.match(m.title,/1040 G6/);}});
test('static contact links use the verified business contacts',()=>{assert.match(html,/tel:\+255746584214/);assert.match(html,/https:\/\/wa\.me\/255746584214/);assert.match(html,/sms:\+255746584214/);assert.match(html,/mailto:scbernard004@gmail\.com/);assert(!html.includes('href="javascript:'));});
test('dynamic WhatsApp and SMS messages use the same contact number',()=>{assert.match(app,/const wa=text=>'https:\/\/wa\.me\/'\+config\.phone/);assert.match(app,/const sms=text=>'sms:\+'\+config\.phone/);assert.match(app,/productSms\(p,currentVariant,'buy'\)/);assert.match(app,/\$\('#bag-sms'\)\.href=sms\(message\)/);});
test('all static local page references exist',()=>{const refs=[...html.matchAll(/(?:src|href)="([^"#?]+)"/g)].map(x=>x[1]).filter(x=>!x.includes(':'));for(const ref of refs)assert(existsSync(resolve(root,ref)),ref);});
test('price labels disclose their supplied-listing source',()=>{assert.match(app,/Price from your supplied listing · Confirm today/);assert.match(html,/Prices are from previous sales listings/);});
test('all catalogue prices are positive and variant base prices are consistent',()=>{for(const p of data.products){assert(Number.isInteger(p.price)&&p.price>0,p.id);for(const v of p.variants)assert(Number.isInteger(v.price)&&v.price>0,`${p.id}: ${v.label}`);if(p.variants.length)assert.equal(p.price,p.variants[0].price,p.id);}});
test('responsive design includes simple desktop and mobile contact layouts',()=>{assert.match(simpleCss,/\.contact-shortcuts\s*\{[^}]*grid-template-columns:repeat\(4/);assert.match(simpleCss,/@media\(max-width:600px\)[\s\S]*\.contact-shortcuts\s*\{[^}]*grid-template-columns:1fr 1fr/);assert.match(simpleCss,/@media\(max-width:359px\)[\s\S]*\.product-grid\s*\{\s*grid-template-columns:1fr/);});
test('page IDs are unique and major controls have accessible labels',()=>{const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length);for(const id of ['language-switch','search','gallery-search','product-dialog','bag-dialog','compare-dialog','media-dialog'])assert(html.includes(`id="${id}"`),id);assert.match(html,/aria-label="Quick contact options"/);});
